-- DOC8 FULL DATABASE SETUP & RESET SCRIPT
-- Run this in your Supabase SQL Editor to sync everything (Notes, Subjects, Notices, Storage)

-- 0. INITIAL CLEANUP (Drop policies to avoid conflicts on re-run)
do $$ 
begin
  -- Drop policies for 'profiles'
  drop policy if exists "Public profiles are viewable by everyone." on profiles;
  drop policy if exists "Users can insert their own profile." on profiles;
  drop policy if exists "Users can update own profile." on profiles;

  -- Drop policies for 'subjects'
  drop policy if exists "Subjects are viewable by everyone." on subjects;
  drop policy if exists "Authenticated users can create subjects" on subjects;
  drop policy if exists "Users can delete own subjects" on subjects;

  -- Drop policies for 'notes'
  drop policy if exists "Notes are viewable by everyone." on notes;
  drop policy if exists "Authenticated users can insert notes." on notes;
  
  -- Drop policies for 'notices'
  drop policy if exists "Notices are viewable by everyone." on notices;
  drop policy if exists "Authenticated users can post notices." on notices;
  drop policy if exists "Users can delete own notices" on notices;

  -- Drop Storage policies
  drop policy if exists "Authenticated users can upload" on storage.objects;
  drop policy if exists "Limit size to 10MB" on storage.objects;
  drop policy if exists "Users can delete own files" on storage.objects;
  drop policy if exists "Anyone can download notes" on storage.objects;
end $$;

-- 1. PROFILES TABLE
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  year text, -- e.g. '1st Year'
  updated_at timestamp with time zone
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- 2. SUBJECTS TABLE
create table if not exists subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  year text not null,
  semester text not null,
  icon text,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users -- Added for ownership
);

alter table subjects enable row level security;

create policy "Subjects are viewable by everyone." on subjects for select using (true);
create policy "Authenticated users can create subjects" on subjects for insert with check (auth.role() = 'authenticated');
create policy "Users can delete own subjects" on subjects for delete using (auth.uid() = user_id);

-- 3. NOTES TABLE
create table if not exists notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  author text,
  file_url text not null,
  file_size text,
  subject_id bigint references subjects(id),
  user_id uuid references auth.users not null
);

alter table notes enable row level security;

create policy "Notes are viewable by everyone." on notes for select using (true);
create policy "Authenticated users can insert notes." on notes for insert with check (auth.role() = 'authenticated');

-- 4. NOTICES TABLE
create table if not exists notices (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  attachment_name text,
  attachment_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  likes integer default 0,
  dislikes integer default 0
);

alter table notices enable row level security;

create policy "Notices are viewable by everyone." on notices for select using (true);
create policy "Authenticated users can post notices." on notices for insert with check (auth.role() = 'authenticated');
create policy "Users can delete own notices" on notices for delete using (auth.uid() = user_id);


-- 5. TRIGGERS (Handle New User)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, year)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', '1st Year')
  on conflict (id) do nothing; -- Prevent error if exists
  return new;
end;
$$;

-- Drop trigger first to prevent duplicates
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 6. STORAGE SETUP (Create bucket if not exists)
insert into storage.buckets (id, name, public) 
values ('notes', 'notes', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Authenticated users can upload" on storage.objects for insert to authenticated with check (bucket_id = 'notes');
create policy "Limit size to 10MB" on storage.objects for insert with check ((metadata->>'size')::int <= 10485760);
create policy "Users can delete own files" on storage.objects for delete using (bucket_id = 'notes' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "Anyone can download notes" on storage.objects for select using (bucket_id = 'notes');
