-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. PROFILES TABLE (Public profiles for users)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. SUBJECTS TABLE (Academic Subjects)
create table subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  year text not null, -- e.g., '1st Year'
  semester text not null, -- e.g., 'Sem 1'
  icon text, -- Icon name string
  color text, -- Color class string
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table subjects enable row level security;

create policy "Subjects are viewable by everyone."
  on subjects for select
  using ( true );

-- Insert default subjects (Example Data)
insert into subjects (name, year, semester, color) values
('Mathematics', '1st Year', 'Sem 1', 'text-orange-500'),
('Physics', '1st Year', 'Sem 1', 'text-violet-500'),
('Computer Science', '1st Year', 'Sem 2', 'text-blue-500');

-- 3. NOTES TABLE (The actual files)
create table notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  author text,
  file_url text not null, -- Cloudinary URL
  file_size text,
  subject_id bigint references subjects(id),
  user_id uuid references auth.users not null
);

alter table notes enable row level security;

create policy "Notes are viewable by everyone."
  on notes for select
  using ( true );

create policy "Authenticated users can insert notes."
  on notes for insert
  with check ( auth.role() = 'authenticated' );

-- Function to handle new user signup (Trigger)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
